import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/layout";
import Jumbotron from "../components/Jumbotron";
import JumbotronContent from "../components/Jumbotron-content";
import Events from "../components/Events";
import ImageSlideGallery from "../components/ImageSlideGallery";
import Locations from "../components/Locations";
import History from "../components/History";
import AboutUs from "../components/AboutUs";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Indian Food Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout home>
          <section style={{ position: "relative" }}>
            <Jumbotron></Jumbotron>
            <div className={styles.jumbotronContent}>
              <JumbotronContent></JumbotronContent>
            </div>
          </section>
          <section>
            <Events></Events>
          </section>
          {
            <section>
              <ImageSlideGallery></ImageSlideGallery>
            </section>
          }
          <section>
            <Locations></Locations>
          </section>
          <section>
            <History></History>
          </section>
          <section>
            <AboutUs></AboutUs>
          </section>
          <section>
            <Contact></Contact>
          </section>
        </Layout>
      </main>

      {
        <footer className={styles.footer}>
          <div>
            <Image
              alt="logo"
              src={"/images/logo.png"}
              width={125}
              height={120}></Image>
          </div>
          <div className={styles.footerMid}>
            <div className={styles.footerCircle}>
              <Image
                alt="arrow-up"
                width={10}
                height={10}
                src={"/images/arrow-up.png"}></Image>
            </div>
            <span>Denna hemsida är skapad med hemsida är skapad</span>
          </div>
          <div className={styles.footerEnd}>
            <Image
              width={96}
              height={32}
              alt="socials"
              src={"/images/socials.png"}></Image>

            <span>© Indian Food Website 2022 • All rights reserved.</span>
          </div>
        </footer>
      }
    </div>
  );
}
